# -*- coding: utf-8 -*-
"""DS3402 - Group10 Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mHiIm3KjfX9CatfnkU59sEZ-2FBtalgQ

# DS 340W PROJECT - HOUSE PRICE PREDICTION
Group 10: Brianna Malone, and Alvaro Tapia
"""

# Importing all the necessary packages and files
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat
import warnings
# ignore all warnings
warnings.filterwarnings("ignore")

from google.colab import drive
drive.mount('/content/drive')

# Reading the datasets
data = pd.read_csv(os.path.join('/content/drive/My Drive/DS340W', 'house_data.csv'), error_bad_lines=False)
data.head()

#Data cleaning process
data = data.drop_duplicates()
data = data.dropna()
print(data.shape)

# Perform feature importance by using Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

X = data.data
y = data.target

# Train a random forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(X, y)

# Get feature importances
importances = clf.feature_importances_
feature_names = data.feature_names

# Sort the features by importance in descending order
indices = np.argsort(importances)[::-1]

# Create a horizontal bar graph of feature importances with the most important features at the top
plt.figure(figsize=(10, 6))
plt.title("Feature Importances")
plt.barh(range(X.shape[1])[::-1], importances[indices][::-1], align="center")
plt.yticks(range(X.shape[1]), [feature_names[i] for i in indices][::-1])
plt.xlim([0, 1])
plt.show()

# Filtering and droping unneccesary parameters for the purpose of investigation
data = data.drop(['', ''], axis=1)
data.head(5)

# Continue the process of coding
# ...